### ISSUE TITLE
DRAFT - Microconsulting Work Statement - API Outreach

### ISSUE THREAD

**Issue by mjunda** [department-of-veterans-affairs/lighthouse#3]
# **DRAFT - Microconsulting Work Statement – API Outreach**

## Background
The Lighthouse program is pivoting VA towards becoming an Application Programming Interface (API) driven digital enterprise, which will establish the Next Generation Open Digital Platform for Veterans and accelerate the transformation in core domains of VA, such as Health, Benefits, Burial and Memorials. This platform will be a system for designing, developing, publishing, operating, monitoring, analyzing, iterating and optimizing VA’s API ecosystem.

## The Play
Utilizing government furnished GitHub environment develop draft version of how a “service” component of Lighthouse can promote transparency and observability, default to public as much as possible. The goal will be for Lighthouse program to develop feedback loop and outreach in a regular and consistent way consistent with the way the API world operates.  

## Deliverable
Draft version of process in markdown language in government furnished GitHub environment.

## Time Box
VA anticipates a 2 week iteration to be sufficient.

## Disclaimer
In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information).  Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network.  Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Evaluation
Vendor will provide a less than one-page description of their understanding of the effort.  Vendor will propose a price for the complete work effort.  VA will determine which vendor’s proposal is most beneficial.  Award may or may not be to the lowest proposed price.

**Comment by ss0ss** [comment]
Hello!

This comment is regarding the use of markdown, and its processes, for the publication of content for this API Outreach work statement. To ensure the most efficient use of Github-as-a-CMS, from our experience, it's strongly recommended that the vendor:

- Be required to provide copy editing and formatting services while using markdown
- NOT be required to conduct VA governance feedback (aka "concurrence") as part of a publication requirement because this will slow down the assumed intent of rapid public feedback
- Be required to provide a style guide that will follow an eventual "API Playbook" 

We believe this would:

1. Ensure that the public-facing nature of this pilot program is free from simple publication errors that would bring undue scrutiny
2. Prevent any unnecessary delays in publication times given the two week timeline
3. Allow for consistency and reduce loss time in style/tone/publication familiarization when vendors switch

Thank you for reading me!

Shaun So
Managing Partner, The So Company
SDVOSB & SBA 8(a)
shaun[at]thesocompany.com
DUNS: 967707774

**Comment by preston** [comment]
+1 for the use of simple Markdown and GitHub repository for this purpose, especially in development of SOW-like work statements.

Regarding appropriate scoping, I would expect most software engineers and small teams to be able to run with a few paragraph synopsis of what the project is for and why it is important, a rough sketch of the core data structures it needs to manage via its API, a (very) short list of the most important user story statements as a bulleted list, and any technical requirements, which in the case of SoF apps would be:

- OpenID Connect / OAuth 2.0 and relevant SMART scopes
- Applicable FHIR profiles, or at least the resource types
- Any functional requirements, e.g. no writeback, HTTP/2, Angular/React over FHIR JSON, Chrome/Edge/Firefox/whatever, 
- Any non-functional requirements, e.g. F/OSS licensing, §508, performance etc

I've had big successes in the past with these sorts of 2-page RFPs. Anything more, though, and nobody is going to bite at this price point.
