### ISSUE TITLE
DRAFT - Microconsulting Work Statement – API Roadmapping

### ISSUE THREAD

**Issue by mjunda** [department-of-veterans-affairs/lighthouse#4]
# **DRAFT - Microconsulting Work Statement – API Roadmapping**

## Background
The Lighthouse program is pivoting VA towards becoming an Application Programming Interface (API) driven digital enterprise, which will establish the Next Generation Open Digital Platform for Veterans and accelerate the transformation in core domains of VA, such as Health, Benefits, Burial and Memorials. This platform will be a system for designing, developing, publishing, operating, monitoring, analyzing, iterating and optimizing VA’s API ecosystem.

## The Play
This is VA’s first iteration to develop a process to orchestrate the entire Lighthouse program on GitHub or similar appropriate platform . Develop plan for each participant to integrate their contribution (service) into the larger program. This will provide a standardized, yet scalable way to address what is being planned, is being delivered, operated, and when services will ultimately be deprecated. Government will provide necessary environment (Currently GitHub). 

## Deliverable
Draft version of process in markdown language in government furnished GitHub environment.

## Time Box
VA anticipates a 2 week iteration to be sufficient.

## Disclaimer
In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information).  Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network.  Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Evaluation
Vendor will detail an approach to identify and prioritize APIs in an enterprise like VA.  Vendor will propose a price for the complete work effort.  VA will determine which vendor’s proposal is most beneficial.  Award may or may not be to the lowest proposed price.

**Comment by preston** [comment]
See [my other comment](https://github.com/department-of-veterans-affairs/lighthouse/issues/5#issuecomment-377309632).

**Comment by RobertLRead** [comment]
Although a complete road map leading to a comprehensive scalable approach is clearly desirable, I wonder if a more achievable and in the short term more directly valuable goal would be to harmonize a smaller number, say 3, APIs?  That is, fully analyze 3 possibly unrelated APIs and not just suggest best practices for all 3 but show how all three can be "harmonized" with modest effort (I do not mean a programming effort here.) Of course this could fail, if the 3 APIs are completely unrelated...but let's imagine that you find 3 that refer to an object, let's say a veteran, using different keys, or different syntax for the keys. A plan for "mappinig" or "unifying" these 3 so that they, for example, all produce similar JSON, all use the same field names, all use the same date formats, would be concrete progress achievable in 2 weeks (it might take longer to get the coding done, depending on contractors involved.)

The beauty of this is that is "Agile" and "Lean" --- you learn and progress as you go. You would want to be prepared to explain this to higher-ups (maybe even Congress) by saying "Although modest, we have standardized 3 APIs in certain ways, which is a beachhead of an approach for addressing the entire enterprise."

This would require a small amount of courage to fight against the voice that says "Don't do anything until we have the whole thing planned out." But in a situation like this, even if you make a misstep, for example, choosing a date format you later decide to change, the fact that 3 are harmonized lowers the cost of that change for all 3.
