### ISSUE TITLE
DRAFT - Microconsulting Work Statement – API Strategy Development

### ISSUE THREAD

**Issue by mjunda** [department-of-veterans-affairs/lighthouse#5]
# **DRAFT - Microconsulting Work Statement – API Strategy Development**

## Background
The Lighthouse program is pivoting VA towards becoming an Application Programming Interface (API) driven digital enterprise, which will establish the Next Generation Open Digital Platform for Veterans and accelerate the transformation in core domains of VA, such as Health, Benefits, Burial and Memorials. This platform will be a system for designing, developing, publishing, operating, monitoring, analyzing, iterating and optimizing VA’s API ecosystem.

## The Play
Develop a strategy in the following areas:
* API Lifecycle – In a diagram lay out a step-by-step list of steps along a modern API lifecycle inside of VA. 
* API Support – Identify how the strategy and operations will be supported within VA
* API Evangelism – Develop a messaging campaign around how API operations will spread internally, and externally

## Deliverable
* One designer quality diagram able to be printed in poster form of API lifecycle.
* White paper 1-2 pages describing strategy and operations. 
* Power Point (3-5 slides) and white paper (1-2 pages) describing messaging campaign and resources required to implement.
 
## Time Box
VA anticipates a 2 week cycle to be sufficient.  

## Disclaimer
In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information).  Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network.  Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Evaluation
Vendor will provide a less than one-page description of their understanding of the API lifecycle.  Vendor will propose a price for the complete work effort.  VA will determine which vendor’s proposal is most beneficial.  Award may or may not be to the lowest proposed price.

**Comment by bdurham500** [comment]
Thanks for your post mjunda. Quick question on strategy messaging;
How closely will the messaging campaign be aligned with the VA brand with external stakeholders in mind?

**Comment by preston** [comment]
Note that I only have passing familiarity with prior VA attempts to do similar things, and feel this would be justified because it's rooted in the reality of where current technology trends are headed, does *not* have VA-specific jargon, and is further evidence by being cousin to many successful examples of how competitive application implementations are exchanged in a scalable manner, such as Apple's, Google's, and Amazon's respective app stores. Without such a (Marketplace) portal as the central hub for Lighthouse deliverables, it's hard to imagine operating something at VA scale with only unstructured links sent via email/GitHub/etc.
