### ISSUE TITLE
DRAFT - Microconsulting Work Statement – VA API Landscape Analysis

### ISSUE THREAD

**Issue by mjunda** [department-of-veterans-affairs/lighthouse#6]
# **DRAFT - Microconsulting Work Statement – VA API Landscape Analysis**

## Background
The Lighthouse program is pivoting VA towards becoming an Application Programming Interface (API) driven digital enterprise, which will establish the Next Generation Open Digital Platform for Veterans and accelerate the transformation in core domains of VA, such as Health, Benefits, Burial and Memorials. This platform will be a system for designing, developing, publishing, operating, monitoring, analyzing, iterating and optimizing VA’s API ecosystem.

## The Play
Perform a Landscape Analysis/Mapping of current state VA to discover what is currently available within organization with regard to APIs. Key focus is to define Internal Resources including web services, APIs, teams, and resources that currently exist. Analysis must detail the external objectives of doing APIs?

Upon award 10-15 Points of Contact (POC) will be provided to assist in gathering needed data along with artifact documents collected to date.

## Deliverable
An excel sheet with detailed information about the resources and a 3-4 slide PowerPoint that generally describes the current state and external objectives. Other methods of presenting information may be agreed upon.

## Time Box
VA anticipates a 2 week cycle to be sufficient.  Additional time may be provided to allow for contacting the full list of POCs or any additional POCs identified during performance.

## Disclaimer
In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information).  Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network.  Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Evaluation
Vendor will provide a less than one-page description of ability to identify and collect the necessary data, and present it appropriately to the Government.  Vendor will propose a price for the complete work effort.  VA will determine which vendor’s proposal is most beneficial.  Award may or may not be to the lowest proposed price.

**Comment by ss0ss** [comment]
Hello!

Based on our past experiences coordinating with multiple offices and departments at VA during engagements while conducting VA stakeholder interviews and existing-product analysis, it might be best to limit this first two week engagement to:

- Creating the desired deliverable using existing artifacts on hand at project kick off
- Conducting the initial contact to the 10-15 POC's, but not rely on their returned communications on this specific engagement and consider the initial outreach a deliverable
- Incorporating all feedback received by each of the POC's, as they trickle in for planning the next deliverables on a future two week engagement

We believe this would:

1. Allow for a deeper API landscape review, independent of time-dependent coordination efforts with multiple points of contacts inside a large organization
2. Promote a more risk-averse pricing window in order to accurately forecast project planning hours
3. Give the client a clear understanding of what to expect at the onset of this engagement (and each two week research engagement) in order to minimize time risk because of artifact gathering wait times

Thank you for reading me!

Shaun So
Managing Partner, The So Company
SDVOSB & SBA 8(a)
shaun[at]thesocompany.com
DUNS: 967707774

**Comment by robrasmussen1970** [comment]
These are awesome! I am wondering if your target is the  $3K (FAR 1902) or the new (U.S. Code NDAA Section 806) $10K threshold?  I think that the work described would fit well within the latter?

**Comment by robrasmussen1970** [comment]
I have a few suggestions about the format of these work statements:

1. Perhaps the government can format 'The Play' into a user story with intent language 

(i.e.  In this case:  _As a Program Manager or Contracting Officer I need a Landscape Analysis/Mapping of the current state of API's within VA and external to VA,  so that I have a better understanding of what is currently available within organization with regard to APIs, and so that I know what internal and external objectives are important when considering APIs). _ 

I think this may make it easier for vendors to understand your intent.

2. Assuming the section labeled 'Evaluation' is mostly pertaining to the proposal response, it would be great to have some evaluation criteria (Definition of Done) for the actual delivery (i.e. in this case the Landscape Analysis).  

3. If at all possible a short list of supporting objectives (1 page) would also be useful to support more context.  

Thanks for listening!!

**Comment by RobertLRead** [comment]
I recommend that analysis should be targeted at improvements. It is important to understand current usage and potential future usage that can be accomplished without major development effort. 
Questions:
*) Will the POCs be able to ask or make available consumers of the APIs in order to gather information on how useful the APIs are and how they might be improved?
*) Is it desired to make (what sounds like) mostly internal APIs externally available?
*) Will the POCs be able to "look into systems" or will they be expected to know what is available? It sounds as if the contractor will not be looking at VA systems directly.


Recommendations:
* Ask for a clear analysis of who uses, are they internal/external, frequency of use, subjective value of the APIs (I'm assuming that is not sensitive information exceeding the scope here.)
* Ask (in one sentence) for an analysis of API Management best practices, such as:
   1. Are keys being used?
   2. Is throttling in place?
   3. Is documentation adequate?
   4. Is the output flexible (that is, available in CVS, HTML, and JSON, or some internal format)?
